---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  # - name: centos-6
  #   image: centos:6
  - name: centos-7
    image: centos:7
  # - name: debian-wheezy
  #   image: debian:wheezy
  - name: debian-jessie
    image: debian:jessie
  - name: debian-stretch
    image: debian:stretch
  - name: ubuntu-trusty
    image: ubuntu:trusty
  - name: ubuntu-xenial
    image: ubuntu:xenial
  - name: ubuntu-zesty
    image: ubuntu:zesty

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  options:
    disable-pytest-warnings: True
    v: True
  lint:
    name: flake8
